### PR TITLE
Fix logging in over ssh

### PR DESCRIPTION
**Pull request by gjedeer**

### CODE REVIEW

**Comment by gjedeer** [comment]
Found an even better way which fixes SSH and firewall in all command:
`mount -t devtmpfs devtmpfs /dev`

Now, if I only could figure out how to make procd run it - doesn't work as a S00 service.

**Comment by cvmiller** [comment]
Thanks for your improvement, and work on ssh access.

I didn't find the fix of adding the node ptmx to help after adding your mount /dev to get things booting to help.

I have updated the init.sh script to issue the mount command
```mount -t devtmpfs devtmpfs /dev```

I left the firewall stuff in for now, as I haven't had a chance to test. I will be traveling for the next couple of weeks, and may be a bit slower on responding. But thanks for working on the ssh access issue. The "old" way of ```ssh "/bin/sh" -i ``` continues to work for now.

**Comment by gjedeer** [comment]
After more testing, I've found that the mount command sometimes worked and, more often, not. When it did, there was a /dev/ directory with a lot of files.

Anyway, the mknod command from my pull request worked good, ssh /bin/sh wasn't needed any more.

I've also found the good news that just yesterday, container support was merged into openwrt, so the next stable version is not going to need this workaround.  Basically the patches from https://github.com/mikma/lxd-openwrt which you linked will be upstream.

**Comment by cvmiller** [comment]
Interesting. In my testing, the mount command worked through several reboots. That is good news that the procd will be patched to make this unnecessary in future releases.

I am on the road. When I get back, I'll revert the mount command change, and add your mknod command, and do some more testing. Thanks for the help.

**Comment by cvmiller** [comment]
Back from travels. Have updated the script adding the mknod  -m 666 /dev/ptmx c 5 2, and keeping the "mount /dev" as an option using -m. Tested here, and it seems to work (version 0.93).

**Comment by gjedeer** [comment]
Glad to hear it works. Personally I moved to using openwrt snapshot. Checks the box of "without recompiling or building from source" which is good for me.

**Pull request closed without merging**
