### PR TITLE
Init all tables

### PR DESCRIPTION
**Pull request by laigor**
Init not only the filter table but also nat mangle and raw tables.

### CODE REVIEW

**Comment by cvmiller** [comment]
I appreciate your suggested changes, however:

Have you experienced the NAT and RAW tables not being initialized? 'iptables -L' only lists the tables, which is a work around to allow the openwrt firewall to restart. It doesn't actually initialized the different tables (perhaps my comment should be changed).

As to the last part, your patch no longer checks that there is an WAN Zone which requires masquerading. The reason that code is there, is in the event the router is running in a IPv6-only environment, there is no need to insert a MASQ rule.

**Comment by laigor** [comment]
After the proposed changes, the openwrt firewall becomes fully operational and can itself creates all NAT rules, including masquerading.

**Comment by laigor** [comment]
In my case, the NAT table was missing after starting openwrt 19.07 (I did not use your init.sh). But after running the iptables -t nat -L command, the table appears.

**Comment by cvmiller** [comment]
Thanks. I have integrated your changes, while retaining the IPv4 check and adding NAT rule at the end.

You may want to open a bug on the IPv4 NAT rule not being inserted in 19.07, as init.sh should no longer be necessary once 19.07 is released.

**Comment by laigor** [comment]
https://github.com/openwrt/openwrt/pull/2525

**Comment by laigor** [comment]
https://bugs.openwrt.org/index.php?do=details&task_id=2575

**Pull request closed without merging**
